In [20]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 23.1
[notice] To update, run: C:\Users\agraw\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [21]:
import numpy as np

In [22]:
a = np.array([8,6,5])
a

array([8, 6, 5])

In [23]:
c= np.array([[3,8,4],[9,3,4],[11,15,17],[19,31,8]])
c

array([[ 3,  8,  4],
       [ 9,  3,  4],
       [11, 15, 17],
       [19, 31,  8]])

In [24]:
d= np.array([[4,8,7],[3,1,5],[6,9,13]])
d

array([[ 4,  8,  7],
       [ 3,  1,  5],
       [ 6,  9, 13]])

In [25]:
d.shape

(3, 3)

In [26]:
e= np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]]])
e

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [27]:
e.shape

(3, 3, 2)

In [28]:
(e[0,2])
(e[0][2])
(d[1:])
(d[1,0:3:1])

array([3, 1, 5])

In [29]:
(e[1,2])
(e[1][2])

array([ 5, 51])

In [30]:
(d[1,0:3:1])

array([3, 1, 5])

In [31]:
(d[1,0:3:1]).shape

(3,)

In [32]:
(e[0:5:1,3:3])

array([], shape=(3, 0, 2), dtype=int32)

In [33]:
(d[1:3:1,1:3:1])

array([[ 1,  5],
       [ 9, 13]])

In [34]:
(d[1:,1])

array([1, 9])

In [35]:
(e[1:3,0:1])

array([[[ 3, 31]],

       [[ 6, 61]]])

In [36]:

x=c+5
x


array([[ 8, 13,  9],
       [14,  8,  9],
       [16, 20, 22],
       [24, 36, 13]])

In [37]:
c[0,:]=[20,40,24]

In [38]:
c

array([[20, 40, 24],
       [ 9,  3,  4],
       [11, 15, 17],
       [19, 31,  8]])

In [39]:
c[:,1]=[20,40,24,469]
c

array([[ 20,  20,  24],
       [  9,  40,   4],
       [ 11,  24,  17],
       [ 19, 469,   8]])

In [40]:
# TO ADD NEW ROW OR COLUMN IN ARRAY
np.append(c,[[1,1,1]], axis = 0)

array([[ 20,  20,  24],
       [  9,  40,   4],
       [ 11,  24,  17],
       [ 19, 469,   8],
       [  1,   1,   1]])

In [41]:
np.append(c,[[34],[1],[41],[51]], axis = 1) #ADDING COLUMN IN ARRAY

array([[ 20,  20,  24,  34],
       [  9,  40,   4,   1],
       [ 11,  24,  17,  41],
       [ 19, 469,   8,  51]])

In [42]:
np.delete(c,1,0)

array([[ 20,  20,  24],
       [ 11,  24,  17],
       [ 19, 469,   8]])

In [43]:
c.reshape(3,4)# for converting the shape of array

array([[ 20,  20,  24,   9],
       [ 40,   4,  11,  24],
       [ 17,  19, 469,   8]])

In [44]:
c.reshape(6,2)

array([[ 20,  20],
       [ 24,   9],
       [ 40,   4],
       [ 11,  24],
       [ 17,  19],
       [469,   8]])

In [45]:
a.dtype # to check datatype

dtype('int32')

In [46]:
a1=np.array([3.4,3,1])
a1

array([3.4, 3. , 1. ])

In [47]:
a1.dtype

dtype('float64')

In [48]:
a1.astype('uint16')

array([3, 3, 1], dtype=uint16)

In [49]:
c.mean(axis=0)

array([ 14.75, 138.25,  13.25])

In [50]:
#nutshell
#we create arrays
#1. np.array()
#2. np.ones()
#3. np.zeroes()
#4. np.arrange()-a range
#5  np.linspace()
#6. np.random.randint()


In [51]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [52]:
np.random.randint(1,15,[3,4])

array([[ 5,  2, 14,  1],
       [14,  7, 10,  3],
       [ 3, 14,  8,  5]])

In [53]:
f=np.array([[1,6,11],[7,5,3],[3,5,7]])
f

array([[ 1,  6, 11],
       [ 7,  5,  3],
       [ 3,  5,  7]])

In [54]:
f.dtype

dtype('int32')

In [2]:
import numpy as np

In [4]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.zeros((2,3), dtype =int )

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.linspace(1,10,10, dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
list(range(1,2,10))

[1]

In [16]:
np.random.randint(1,6,1)

array([3])

In [17]:
np.random.randint(1,6,2)

array([4, 1])

In [18]:
np.random.randint(1,6,[4,3,2])

array([[[5, 3],
        [4, 4],
        [2, 5]],

       [[1, 5],
        [2, 1],
        [4, 3]],

       [[5, 4],
        [4, 1],
        [1, 2]],

       [[5, 4],
        [5, 4],
        [5, 4]]])

In [19]:
np.random.seed(54)
np.random.randint(1,6,[4,3,2])

array([[[3, 2],
        [1, 1],
        [2, 2]],

       [[2, 5],
        [5, 5],
        [5, 1]],

       [[1, 2],
        [4, 3],
        [2, 3]],

       [[5, 2],
        [4, 3],
        [1, 2]]])

In [20]:
np.random.rand(3,4)

array([[0.99695746, 0.30787317, 0.17198668, 0.17538453],
       [0.16382659, 0.58501438, 0.47353556, 0.46075695],
       [0.23515401, 0.85621717, 0.47089378, 0.05458343]])

In [23]:
r=np.loadtxt('somedata.txt',dtype=str)
r

C:\Users\agraw\AppData\Local\Temp\ipykernel_12944\1210224973.py:1: UserWarning: loadtxt: input contained no data: "somedata.txt"
  r=np.loadtxt('somedata.txt',dtype=str)


array([], dtype='<U1')

In [29]:
r=np.loadtxt('somedata.txt',dtype=str)
r

array(['hii', 'this', 'is', 'A', 'file', 'outside', 'python'], dtype='<U7')

In [30]:
r=np.loadtxt('moredata.txt')
r

array([[48., 78., 56., 67.],
       [48., 69., 89., 23.]])

In [34]:
np.savetxt('new.txt',p,delimiter=',')

In [33]:
p=np.random.rand(3,4)
p

array([[0.99325708, 0.19555639, 0.71252488, 0.81638996],
       [0.47105727, 0.26108617, 0.44061904, 0.20938295],
       [0.47290381, 0.23138279, 0.16117695, 0.21706215]])